### ISSUE TITLE
Can you add multiple servers support

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/ark-ios-monitor#4]
ie. more than on server to monitor... 

at least what I'd like to have in an app :) maybe it is already planned and done... I was looking at the app store version...

Best

**Comment by Awalz** [comment]
You are looking to create your own custom servers presets to switch between?

**Comment by kristjank** [comment]
I have more then one server I'd like to monitor/ if its up and running (node).

Ie. Delegate node and other nodes, the view can be the same, just add one step before - to select server (ip, port) from list of saved servers and then view the stats... you

**Comment by Awalz** [comment]
@kristjank #5 PR adds this functionality. Not sure when it will be merged and pushed to the store. If you have a mac and Xcode, you can try it out yourself

**Comment by vrlcrypt** [comment]
I will review the #5 PR in the next few hours, if everything is ok, I will generate a new version and send it to appstore. Thanks guys.

**Comment by kristjank** [comment]
awesome, looking forward to it.

**Comment by vrlcrypt** [comment]
resolved in #5 PR

**Comment by vrlcrypt** [comment]
The new version will probably be available next week in the appstore.
