### ISSUE TITLE
Bounty Contributions

### ISSUE THREAD

**Issue by MLondoro42** [ArkEcosystem/ark-ios-monitor#8]
Hello there,

I am a mobile developer very interested in helping on this project. I have several ideas on ways to improve. Are there any bounties/rewards for fixes or enhancements?

**Comment by Awalz** [comment]
Hello,

Glad to see you are interested in contributing. I cannot comment on the bounties for this project, @vrlc92 would be the person to ask.

If you do want to contribute, here are some enhancements I would like to see:
- Colour/theme options (maybe closer to the new `explorer.ark.io` or desktop wallet theme
- Loading animations for signing in to show activity (in case of long network requests or timeouts)
- Testing of custom servers to ensure they are configured
- Haptic/taptic feedback
- Home screen shortcuts
- Better font handling for larger/smaller phones

Let me know if you need any help as well. Be sure to check out the Android Monitor as well as it also needs some love

Andrew

**Comment by vrlcrypt** [comment]
@MLondoro42, the Ark team monthly rewards community members who contribute (fixes or enhancements) to the projects present at https://github.com/ArkEcosystem/.
